# Generated by Django 4.1.7 on 2023-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_item_alter_user_id_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='images', width_field='image_width'),
        ),
    ]
