# Generated by Django 4.1.7 on 2023-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_item_image_height_item_image_width_alter_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
